apiVersion: apps/v1
kind: Deployment

metadata:
  name: ollama
  namespace: local-rag

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ollama

  template:
    metadata:
      labels:
        app: ollama

    spec:
      containers:
        - name: ollama

          image: ollama/ollama

          ports:
            - containerPort: 11434
