from pypdf import PdfReader
from pathlib import Path
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
from qdrant_client import QdrantClient
from qdrant_client.models import VectorParams, Distance
from qdrant_client.models import PointStruct
from qdrant_client.http import models
import os



BASE_DIR = Path(__file__).resolve().parent
pdf_path = BASE_DIR / "data" / "DevOps1.pdf"

# Read PDF
reader = PdfReader(pdf_path)

# Extract text
text = ""

# Create splitter
# each chunk will have 500 characters and an overlap of 50 characters between chunks
# meaning that the last 50 characters of one chunk will be the first 50 characters of the next chunk
splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=100
)

#Create page-aware chunks
documents = []

for page_num, page in enumerate(reader.pages):

    page_text = page.extract_text()
    
    if not page_text:
        continue

    page_chunks = splitter.split_text(page_text)

    for chunk in page_chunks:

        documents.append({
            "text": chunk,
            "page": page_num + 1
        })



# Print info
print(f"Total chunks: {len(documents)}")

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Generate embeddings
texts = [doc["text"] for doc in documents]

embeddings = model.encode(texts)

# Connect Qdrant
client = QdrantClient(
    host=os.getenv("QDRANT_HOST", "qdrant"),  # Use the environment variable or default to "qdrant"
    port=6333
)


#create collection in the Qdrant database to store the vectors. The collection is named "documents" and it is configured to store vectors of size 384 (the size of the embeddings generated by the model) and to use cosine distance for similarity search.

if not client.collection_exists(collection_name="documents"):
    client.create_collection(
        collection_name="documents",
        vectors_config=VectorParams(
            size=384,
            distance=Distance.COSINE
        )
    )
    print("Collection created")
# Create points
points = []

for i, vector in enumerate(embeddings):
    points.append(
        PointStruct(
            id=i,
            vector=vector.tolist(),
            payload={
                "text": documents[i]["text"],
                "page": documents[i]["page"]
            }
        )
    )

# Upload
client.upsert(
    collection_name="documents",
    points=points
)

print("Vectors uploaded successfully")       