apiVersion: apps/v1
kind: Deployment

metadata:
  name: qdrant
  namespace: local-rag

spec:
  replicas: 1

  selector:
    matchLabels:
      app: qdrant

  template:
    metadata:
      labels:
        app: qdrant

    spec:
      containers:
        - name: qdrant
          image: qdrant/qdrant

          ports:
            - containerPort: 6333

          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage

      volumes:
        - name: qdrant-storage
          persistentVolumeClaim:
            claimName: qdrant-pvc
