apiVersion: v1
kind: Service

metadata:
  name: rag-api
  namespace: local-rag

spec:
  type: NodePort
  selector:
    app: rag-api

  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 31234
